[package]
name = "http-server"
version = "0.1.0"
edition = "2021"
authors = ["human9000"]

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }


[profile.release]
opt-level = 3
lto = "thin"
